list(REMOVE_DUPLICATES LIBSUFFIX)
file(STRINGS "${MANIFEST}" zlib_files)

foreach(file ${zlib_files})
    get_filename_component(file_sfx "${file}" EXT)
    foreach(sfx ${LIBSUFFIX})
        if(file_sfx MATCHES "${sfx}")
            if(EXISTS "${file}" OR IS_SYMLINK "${file}")
                message(STATUS "cmake -E remove -f ${file}")
                execute_process(COMMAND ${CMAKE_COMMAND} -E remove -f ${file})
            else()
                message(FATAL_ERROR "File from manifest doest not exist: [${file}]")
            endif()
        endif()
    endforeach()
endforeach()
