#pragma once
#include "details/h5ppAttributeProperties.h"
#include "details/h5ppConstants.h"
#include "details/h5ppDatasetProperties.h"
#include "details/h5ppFile.h"
#include "details/h5ppFileCounter.h"
#include "details/h5ppHdf5.h"
#include "details/h5ppLogger.h"
#include "details/h5ppTextra.h"
#include "details/h5ppType.h"
#include "details/h5ppTypeCheck.h"
#include "details/h5ppUtils.h"
#include <hdf5.h>
#include <hdf5_hl.h>
#include <iomanip>
#include <iostream>
#include <optional>
#include <string>
