cmake_minimum_required(VERSION 3.15)
project(h5pp-tests CXX)

find_package(Catch2 3 REQUIRED)

file(GLOB TESTS_ROOT CONFIGURE_DEPENDS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.cpp")
file(GLOB TESTS_V1   CONFIGURE_DEPENDS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "v1/*.cpp")
set(TESTS ${TESTS_ROOT} ${TESTS_V1})
file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/output)
file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/v1/output)
add_custom_target(h5pp-test-all)
foreach (test ${TESTS})
    get_filename_component(test_src ${test} NAME)
    get_filename_component(test_nwe ${test} NAME_WE)
    get_filename_component(test_dir ${test} DIRECTORY)
    set(test_id ${test_nwe})
    if (test_dir)
        string(REPLACE "/" "-" test_dir_id ${test_dir})
        set(test_id ${test_dir_id}-${test_nwe})
    endif ()
    add_executable(h5pp-${test_id} ${test})
    target_link_libraries(h5pp-${test_id} PRIVATE h5pp Catch2::Catch2)
    set(test_output_dir output/)
    if (test_dir)
        set(test_output_dir ${test_dir}/output/)
    endif ()
    target_compile_definitions(h5pp-${test_id} PRIVATE H5PP_TEST_DIR=\"${test_output_dir}\")
    add_test(NAME h5pp-${test_id} WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} COMMAND h5pp-${test_id})
    if(MSVC)
        target_compile_definitions(h5pp-${test_id} PRIVATE _SILENCE_NONFLOATING_COMPLEX_DEPRECATION_WARNING)
        set_target_properties(h5pp-${test_id} PROPERTIES LINK_FLAGS "/ignore:4099")
    endif()
    if(H5PP_ENABLE_COVERAGE)
        target_compile_options(h5pp-${test_id} PRIVATE --coverage)
        target_link_options(h5pp-${test_id} PRIVATE --coverage)
    endif()
    add_dependencies(h5pp-test-all h5pp-${test_id})
    list(APPEND test_tgt_list h5pp-${test_id})
    set(test_pch_group root)
    if(test_dir MATCHES "^v1($|/)")
        set(test_pch_group v1)
    endif()
    list(APPEND test_tgt_list_${test_pch_group} h5pp-${test_id})
endforeach()


# Speed up compilation with precompiled headers
if(H5PP_ENABLE_PCH)
    if(COMMAND target_precompile_headers)
        foreach(test_pch_group root v1)
            unset(first_tgt)
            foreach (tgt ${test_tgt_list_${test_pch_group}})
                # Later CMake versions will only include system header paths for pch generation
                target_include_directories(${tgt} SYSTEM INTERFACE ../include)
                if(NOT TARGET ${first_tgt})
                    target_precompile_headers(${tgt} PRIVATE <h5pp/h5pp.h>)
                    set(first_tgt ${tgt})
                else()
                    target_precompile_headers(${tgt} REUSE_FROM ${first_tgt})
                endif()
            endforeach()
        endforeach()
    endif()
endif()
