cmake_minimum_required(VERSION 3.15)
# Print host properties
cmake_host_system_information(RESULT _host_name QUERY HOSTNAME)
cmake_host_system_information(RESULT _proc_type QUERY PROCESSOR_DESCRIPTION)
cmake_host_system_information(RESULT _os_name QUERY OS_NAME)
cmake_host_system_information(RESULT _os_release QUERY OS_RELEASE)
cmake_host_system_information(RESULT _os_version QUERY OS_VERSION)
cmake_host_system_information(RESULT _os_platform QUERY OS_PLATFORM)

message(STATUS "| H5PP HOST INFO")
message(STATUS "|---------------------------")
message(DEBUG  "| CMake Version ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION}")
message(DEBUG  "| ${_host_name}")
message(STATUS "| ${_os_name} ${_os_platform} ${_os_release}")
message(DEBUG  "| ${_proc_type}")
message(DEBUG  "| ${_os_version}")
message(STATUS "|---------------------------")

# Print all CMake options
message(STATUS "| H5PP BUILD INFO:")
message(STATUS "|-----------------------------")
message(STATUS "| CMAKE_BUILD_TYPE         : ${CMAKE_BUILD_TYPE}")
message(DEBUG  "| CMAKE_PREFIX_PATH        : ${CMAKE_PREFIX_PATH}")
message(DEBUG  "| CMAKE_INSTALL_PREFIX     : ${CMAKE_INSTALL_PREFIX}")
message(DEBUG  "| BUILD_SHARED_LIBS        : ${BUILD_SHARED_LIBS}")
message(STATUS "| H5PP_PACKAGE_MANAGER     : ${H5PP_PACKAGE_MANAGER}")
message(DEBUG  "| H5PP_DEPS_BUILD_DIR      : ${H5PP_DEPS_BUILD_DIR}")
message(DEBUG  "| H5PP_DEPS_INSTALL_DIR    : ${H5PP_DEPS_INSTALL_DIR}")
message(STATUS "| H5PP_BUILD_EXAMPLES      : ${H5PP_BUILD_EXAMPLES}")
message(STATUS "| H5PP_ENABLE_TESTS        : ${H5PP_ENABLE_TESTS}")
message(STATUS "| H5PP_ENABLE_EIGEN3       : ${H5PP_ENABLE_EIGEN3}")
message(STATUS "| H5PP_ENABLE_SPDLOG       : ${H5PP_ENABLE_SPDLOG}")
message(STATUS "| H5PP_ENABLE_FMT          : ${H5PP_ENABLE_FMT}")
message(STATUS "| H5PP_ENABLE_MPI          : ${H5PP_ENABLE_MPI}")
message(DEBUG  "| H5PP_IS_SUBPROJECT       : ${H5PP_IS_SUBPROJECT}")
message(DEBUG  "| H5PP_PREFIX_ADD_PKGNAME  : ${H5PP_PREFIX_ADD_PKGNAME}")
message(STATUS "|-----------------------------")

