if(H5PP_ENABLE_CCACHE)
    find_program(CCACHE_PROGRAM ccache)
    if(CCACHE_PROGRAM)
        set(H5PP_CCACHE_ACTIVE FALSE)
        foreach(lang C CXX)
            set(launcher_var CMAKE_${lang}_COMPILER_LAUNCHER)
            set(launcher_val "${${launcher_var}}")
            if(launcher_val)
                if(launcher_val MATCHES "ccache")
                    message(STATUS "h5pp: ${launcher_var} already uses ccache: ${launcher_val}")
                    set(H5PP_CCACHE_ACTIVE TRUE)
                else()
                    message(STATUS "h5pp: leaving user-defined ${launcher_var} unchanged: ${launcher_val}")
                endif()
            else()
                set(${launcher_var} "${CCACHE_PROGRAM}" CACHE STRING "${lang} compiler launcher" FORCE)
                message(STATUS "h5pp: enabling ccache for ${lang} compiler via ${CCACHE_PROGRAM}")
                set(H5PP_CCACHE_ACTIVE TRUE)
            endif()
        endforeach()
        if(H5PP_ENABLE_PCH AND H5PP_CCACHE_ACTIVE)
            message(STATUS "h5pp: detected ccache + pch: consider setting ccache sloppiness to include_file_mtime,pch_defines,time_macros")
        endif()
    else()
        message(STATUS "h5pp: H5PP_ENABLE_CCACHE is ON, but no ccache executable was found")
    endif()
endif()
