name: macOS 15

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    name: ${{ matrix.compiler }}-${{ matrix.manager }}
    runs-on: macos-15
    permissions:
      contents: read
    env:
      cache-name: cache-${{ matrix.compiler }}-${{ matrix.manager }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_SLOPPINESS: include_file_mtime,pch_defines,time_macros
      CCACHE_MAXSIZE: 384M
    strategy:
      fail-fast: false # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: cl,   manager: cmake, asan: true  }
          - { compiler: cl,   manager: conan, asan: false }
          - { compiler: cl,   manager: find,  asan: false }

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: lukka/get-cmake@v4.2.0
      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        if: matrix.manager == 'conan'
        with:
          python-version: '3.x'

      - name: Prepare cache directories
        run: |
          mkdir -p "$CCACHE_DIR" ~/.conan2 install/github-actions-${{ matrix.manager }}

      - name: Setup ccache + dependency-provider cache
        uses: actions/cache@v4.2.0
        if: matrix.manager == 'cmake'
        with:
          path: |
            ${{ env.CCACHE_DIR }}
            install/github-actions-${{ matrix.manager }}
          key: ${{ github.workflow }}-${{ env.cache-name }}

      - name: Setup ccache + conan cache
        uses: actions/cache@v4.2.0
        if: matrix.manager == 'conan'
        with:
          path: |
            ${{ env.CCACHE_DIR }}
            ~/.conan2
          key: ${{ github.workflow }}-${{ env.cache-name }}

      - name: Setup ccache cache
        uses: actions/cache@v4.2.0
        if: matrix.manager == 'find'
        with:
          path: |
            ${{ env.CCACHE_DIR }}
          key: ${{ github.workflow }}-${{ env.cache-name }}

      - name: Setup build tools
        run: |
          brew install ccache ninja
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Configure ccache
        run: |
          ccache --set-config=max_size=${CCACHE_MAXSIZE}
          ccache --show-config

      - name: Setup brew packages
        if: matrix.manager == 'find'
        run: brew install hdf5 spdlog fmt eigen zlib catch2

      - name: Setup conan
        if: matrix.manager == 'conan'
        run: |
          pip install conan
          conan profile detect --force

      - name: Run CMakePreset
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'github-actions-${{ matrix.manager }}'
          configurePresetAdditionalArgs: "['-DH5PP_ENABLE_ASAN=${{ matrix.asan && 'TRUE' || 'FALSE' }}']"
          buildPreset: 'github-actions-${{ matrix.manager }}'
          testPreset: 'github-actions-${{ matrix.manager }}'

      - name: Show ccache stats
        run: ccache --show-stats
