name: Windows 2022

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    name: ${{ matrix.compiler }}-${{ matrix.manager }}
    runs-on: windows-2022
    env:
      cache-name: cache-${{ matrix.compiler }}-${{ matrix.manager }}
    strategy:
      fail-fast: true # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: cl, manager: conan }
          - { compiler: cl, manager: cmake }

    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Setup Python
        uses: actions/setup-python@v4
        if: contains(matrix.manager, 'conan')
        with:
          python-version: '3.x'

      - name: Setup caches
        id: h5pp-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2
            install/github-actions-${{ matrix.manager }}
          key: ${{ github.workflow }}-${{ env.cache-name }}

      - name: Setup conan
        if: matrix.manager == 'conan'
        run: |
          pip install conan
          conan profile detect --force

      - name: Run CMakePreset
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'github-actions-${{ matrix.manager }}-win'
          buildPreset: 'github-actions-${{ matrix.manager }}-win'
          buildPresetAdditionalArgs: "['--config Debug']"
          testPreset: 'github-actions-${{ matrix.manager }}-win'
          testPresetAdditionalArgs: "['--build-config=Debug']"
